services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      LASTFM_API_KEY: ${LASTFM_API_KEY}
      LASTFM_SHARED_SECRET: ${LASTFM_SHARED_SECRET}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      AWS_HOST: ${AWS_HOST}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build: ./backend
    command: celery -A backend worker -l info --pool=solo
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    depends_on:
      - backend
      - redis

  celery-beat:
    build: ./backend
    command: celery -A backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
    depends_on:
      - backend
      - redis

  flower:
    build: ./backend
    image: mher/flower
    command: celery -A backend flower --port=5555
    ports:
      - "5555:5555"
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      CELERY_BROKER_URL: redis://redis:6379/0

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mysql_data:
